### PR TITLE
Update package.json

### PR DESCRIPTION
**Pull request by Djinne**
You didn't fix "Fix issue with react-native package duplication"

### CODE REVIEW

**Comment by cdra0624** [comment]
We desire this pull request is merged 🙏 🙏 🙏

**Comment by kawoka** [comment]
@thethanghn check this pr please...

**Comment by mkharibalaji** [comment]
@thethanghn - Please release this merged PR as a new version as it is really important and can't able to delete everytime react-native folder in node_modules everytime i install a new package.

**Comment by vishnuindrabalan** [comment]
+1 for the new release

**Pull request merged**
