### PR TITLE
Fix depreciated override

### PR DESCRIPTION
**Pull request by Sylvain-L**
@Override depreciated in [v47](https://github.com/facebook/react-native/releases/tag/v0.47.0) of react-native

### CODE REVIEW

**Comment by punksta** [comment]
any updates? Can't use this plugin with new react-native without fix

**Comment by zarcode** [comment]
@GoldenowlConsultingCompany please merge this asap

**Comment by tiberiumihai** [comment]
@GoldenowlConsultingCompany This should be merged and also changed the react-native dependency to version > 0.47.

More info here: https://github.com/react-native-community/react-native-blur/pull/226

**Comment by tiberiumihai** [comment]
Maybe someone has the same problem.
I did a trick using gradle until this PR will be merged.

I copied TwitterSigninPackage.java with commented @Override in android/app/TwitterSigninPackage.java.

```
...
   //@Override
    public List<Class<? extends JavaScriptModule>> createJSModules() {
        return Collections.emptyList();
    }
...
```

Then I've added a gradle task to copy this file before compiling the dependencies in android/app/build.gradle

```
...
gradle.projectsEvaluated {
  preBuild.dependsOn(fixTwitterSignIn)
}

task fixTwitterSignIn(type: Copy) {
  from "."
  into '../../node_modules/react-native-twitter-signin/android/src/main/java/com/goldenowl/twittersignin'
  include('TwitterSigninPackage.java')
  doLast {
    println "TwitterSignIn FIXED !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
  }
}

dependencies {
    compile project(':react-native-twitter-signin')
...
```

**Comment by elliscwc** [comment]
@thethanghn 
Many thanks if you could merge this! can't use this package without this fix. on v0.49 React native

**Comment by elliscwc** [comment]
@thethanghn @GoldenowlConsultingCompany 
any news?

**Pull request merged**
